Extend-product-service-with-single-product-getter_CU-jfb8wq
lpboucher/dak-coffee-wholesale pull request #11
Opened 2021-05-10 14:11 UTC by a-wilkes

2021-05-10 14:11 UTC, a-wilkes commented
Task linked: [CU-jfb8wq Extend product service with single product getter](https://app.clickup.com/t/jfb8wq)

2021-05-10 16:48 UTC, lpboucher requested changes
Looks good, from my side.

Maybe you can rebase on the product-service after you have made the changes there

2021-05-10 16:48 UTC, lpboucher commented on src/app/shared/models/classes/product.interface.ts
> +    slug: string;
nice, this should indeed be a property of product

2021-05-10 16:48 UTC, lpboucher commented on src/app/core/products/product.service.ts
> +    getOne(slug: string): Observable<Coffee | undefined> {
Typescript complaining about result of find being undefined right?

Going forward, we will have an endpoint to getasingle product and we will route to a 404 page if the slug does not exist. So we can leave as is for now

2021-05-11 12:46 UTC, lpboucher approved these changes

2021-05-11 12:49 UTC, merged