Single-product-page_CU-jfb8tb
lpboucher/dak-coffee-wholesale pull request #12
Opened 2021-05-11 14:05 UTC by a-wilkes

2021-05-11 14:05 UTC, a-wilkes commented
Task linked: [CU-jfb8tb Single product page](https://app.clickup.com/t/jfb8tb)

2021-05-11 14:05 UTC, lpboucher commented
Task linked: [CU-jfb8tb Single product page](https://app.clickup.com/t/jfb8tb)

2021-05-12 07:23 UTC, lpboucher requested changes

2021-05-12 07:23 UTC, lpboucher commented on src/app/modules/products/pages/single-product/single-product.page.html
> +<div *ngIf="product | async as c">
app does not compile because product does not exist, should be product$

2021-05-12 07:23 UTC, lpboucher commented on src/app/modules/products/pages/single-product/single-product.page.html
> +    <h1>{{ c.name }}</h1>
We should use desriptive variable names.

Here we can either change c to currentProduct or change product$ to currentProduct$ and then c to product

2021-05-12 07:23 UTC, lpboucher commented on src/app/modules/products/pages/single-product/single-product.page.ts
> +    product$?: Observable<Product | undefined>;
I see why we need undefined as well. Realistically, when we request data from the server, we may actually redirect to a separate.page if the slug does not exist, so getOne should never return undefined.

Okay to leave as is for now, we will correct later

2021-05-12 07:23 UTC, lpboucher commented on src/app/modules/products/pages/single-product/single-product.page.ts
> +                const slug = params.get("slug");
here we should use routeSnapshot to get params synchronously:

this.slug = this.route.snapshot.paramMap.get("slug");

see https://angular.io/api/router/ActivatedRouteSnapshot

2021-05-12 09:25 UTC, lpboucher approved these changes

2021-05-12 09:25 UTC, merged