Login-form_CU-hh70ac
lpboucher/dak-coffee-wholesale pull request #15
Opened 2021-05-12 14:49 UTC by a-wilkes

2021-05-12 14:49 UTC, a-wilkes commented
Task linked: [CU-hh70ac Login form](https://app.clickup.com/t/hh70ac)

2021-05-12 14:49 UTC, lpboucher commented
Task linked: [CU-hh70ac Login form](https://app.clickup.com/t/hh70ac)

2021-05-16 12:47 UTC, lpboucher requested changes
I have also added the tailwind forms plugin.

See here for some basic classes: https://tailwindcss-custom-forms.netlify.app/

2021-05-16 12:47 UTC, lpboucher commented on src/app/modules/login/pages/login/login.page.ts
> +        const VALID_FORM_STATUS = "VALID";
we should declare this as a type in shared/models/types

2021-05-16 12:47 UTC, lpboucher commented on src/app/modules/login/pages/login/login.page.ts
> +        const input = this.loginForm.value;
it is always best practice to access form fields in getters, e.g.:

get email() {
        return this.loginForm.get("email").value;
    }

2021-05-18 16:46 UTC, lpboucher approved these changes

2021-05-18 16:46 UTC, lpboucher commented on src/app/modules/login/pages/login/login.page.ts
> +    get email(): string {
getters should be placed above the constructor.

Okay for now, we can change it up later

2021-05-18 16:47 UTC, merged