Sidebar-routing_CU-jqaqd8
lpboucher/dak-coffee-wholesale pull request #20
Opened 2021-05-18 15:15 UTC by a-wilkes

2021-05-18 15:15 UTC, a-wilkes commented
Task linked: [CU-jqaqd8 Sidebar routing](https://app.clickup.com/t/jqaqd8)

2021-05-18 15:15 UTC, lpboucher commented
Task linked: [CU-jqaqd8 Sidebar routing](https://app.clickup.com/t/jqaqd8)

2021-05-18 15:23 UTC, a-wilkes commented
Ok, so this one ended up taking a while (mostly due to css stuff not playing along) and turned out to maybe be more of a change that you were perhaps intending. Essentially, to process the new navigation list under *constants*, I though it would be better to make a new component so that it could handle all the logic w.r.t. things being clicked/focussed etc. instead of trying to put this into the HTML for the sidebar. Hopefully it looks ok, though I'm not sure how I feel about the submenus—it might be better to have the parents of submenus only open and close the submenu, instead of having them link to a parent route (I did it this way since I thought you'd want a page that links to all products, but you didn't mention it in the items you wanted as children of the main products page in the todo list. You might think of a better way of doing this, if so let me know—I'm happy to keep working on it!)

2021-05-18 20:29 UTC, lpboucher requested changes
Well done man! This was really good. The comments I have are mainly because it was done well!

I think generally, we do not really need the click handlers in the navitem component. We can achieve the same behaviors by opening if link is active or on hover.

To do that, we can use pseudo-selectors:
1) target sibling of .nav-item-active + .nav-item-children-container-open
2) .nav-item:hover + .nav-item-children-container-open

Happy to discuss/explain. Well done!

2021-05-18 20:29 UTC, lpboucher commented on src/app/modules/backbone/components/nav-item/nav-item.component.scss
> +    @apply w-1/2 z-50;
can remove the w-1/2

2021-05-18 20:29 UTC, lpboucher commented on src/app/modules/backbone/components/nav-item/nav-item.component.html
> +        <app-nav-item [rawNavData]="child" [parentLink]="link" (click)="onClickChild()"></app-nav-item>
instead of passing the whole object, we should pass individual properties:

@Input label: ...
@Input link: ...

That way, we can pass link to children as `${parent}${child}

Also makes it more readable

2021-05-18 20:29 UTC, lpboucher commented on src/app/modules/backbone/components/nav-item/nav-item.component.scss
> +    @apply underline;
can apply the same style as when hovering (see line5)

2021-05-18 20:29 UTC, lpboucher commented on src/app/modules/backbone/components/nav-item/nav-item.component.ts
> +    @Input() rawNavData!: NavigationItemType;
pass individual properties of the object

2021-05-18 20:29 UTC, lpboucher commented on src/app/modules/backbone/components/nav-item/nav-item.component.ts
> +    isOpen = false;
isOpen should likely be defined in the sidebar component

2021-05-18 20:43 UTC, lpboucher commented
I was expecting it would take a bit more time. It is quite common, but is actually quite complex in css.

I agree with the use of another component. I think my description of the ticket was in no man’s land… a little too detailed to do only the css, and not detailed enough to really get into the full functionality.

You did really well though. I have added a lot of comments so we can review together, will be a good learning experience!
On 18 May 2021, 17:24 +0200, a-wilkes ***@***.***>, wrote:
> Ok, so this one ended up taking a while (mostly due to css stuff not playing along) and turned out to maybe be more of a change that you were perhaps intending. Essentially, to process the new navigation list under constants, I though it would be better to make a new component so that it could handle all the logic w.r.t. things being clicked/focussed etc. instead of trying to put this into the HTML for the sidebar. Hopefully it looks ok, though I'm not sure how I feel about the submenus—it might be better to have the parents of submenus only open and close the submenu, instead of having them link to a parent route (I did it this way since I thought you'd want a page that links to all products, but you didn't mention it in the items you wanted as children of the main products page in the todo list. You might think of a better way of doing this, if so let me know—I'm happy to keep working on it!)
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-05-19 13:00 UTC, a-wilkes commented
Ok, so I should have made all the changes we spoke about, the only issue is that I couldn't work out how to close the menus in the mobile version of the site when the user is scrolling. Any ideas? (also note that the little menu arrows are still there, I've just hidden them when the menu is forced open/currently active since it's a bit confusing as you expect to be able to click it to close the menu, and obviously you can't).

2021-05-23 19:32 UTC, lpboucher commented
Nice one. I am accepting this.

There is a bit of a bug at the moment (will create a ticket to fix). If you click on one of the sub-menus, you see the route will blink but revert back to /products.

Let's fix it in another ticket

2021-05-23 19:32 UTC, merged