Gridlist-component_CU-j56bn1
lpboucher/dak-coffee-wholesale pull request #25
Opened 2021-05-26 11:53 UTC by a-wilkes

2021-05-26 11:53 UTC, a-wilkes commented
Task linked: [CU-j56bn1 Grid/list component](https://app.clickup.com/t/j56bn1)

2021-05-26 11:53 UTC, lpboucher commented
Task linked: [CU-j56bn1 Grid/list component](https://app.clickup.com/t/j56bn1)

2021-05-30 15:14 UTC, lpboucher requested changes
Some minor changes needed. This was well done

2021-05-30 15:14 UTC, lpboucher commented on src/app/modules/products/components/product-list/product-list.component.html
> +    <div class="product-card-container" *ngFor="let product of products">
this div is not needed. We can use the ngFor loop and pass the product on the app-product-card element

By removing this intermediary div, we can more easily target children of the grid item. Also, the product-card-container class is not needed (see comment below)

2021-05-30 15:14 UTC, lpboucher commented on src/app/modules/products/components/product-list/product-list.component.scss
>      @apply p-4;
this class is not needed. Here, adding padding around the individual elements in the grid should be the responsibility of the grid layout. It may seem counterintuitive because it has to be applied on each element, but you can use grid-gap for gap between elements in a grid

2021-05-30 15:14 UTC, lpboucher commented on src/app/modules/products/pages/product/product.page.html
>  </div>
Here it is becoming a bit confusing (I just noticed). featured-product-card is wraped by the grid-list while product-list uses the grid-list internally.

I think we can now remove the product-list and simply use the grid-list here (as we do for featured-product-card)... anyway , i will create another ticket

2021-05-30 15:14 UTC, lpboucher commented on src/app/modules/products/pages/product/product.page.scss
>      @apply p-4;
these intermediary classes/div are not needed. But we can fix in another ticket

2021-05-30 15:14 UTC, lpboucher commented on src/app/shared/components/grid-list/grid-list.component.ts
> +    getColumnClass(): string {
if a method takes in no parameters and only derives value from another property, we should use class getters.

2021-05-30 15:14 UTC, lpboucher commented on src/app/shared/components/grid-list/grid-list.component.ts
> +    private clampColumnValue(columnValue: number): number {
I like this method. It seems likely that we will use it some other place correct?

This is the kind of transformation that is a great use case for a pipe, pipes can also be used in component files by injecting them in the constructor and calling the transform method. I will explain in another ticket

2021-05-31 20:25 UTC, lpboucher approved these changes

2021-05-31 20:25 UTC, lpboucher commented on src/app/shared/components/grid-list/grid-list.component.ts
> +    }
this is a bit of an overkill. We are only applying classes here, so any invalid values will not throw errors or bugs it simply will not apply any styles

simple string interpolation will do

2021-05-31 20:25 UTC, lpboucher commented on src/app/shared/components/grid-list/grid-list.component.ts
> +    }
done

2021-05-31 20:25 UTC, merged