Clamp-pipe_CU-knavr6
lpboucher/dak-coffee-wholesale pull request #27
Opened 2021-05-31 13:11 UTC by a-wilkes

2021-05-31 13:11 UTC, a-wilkes commented
Task linked: [CU-knavr6 Clamp pipe](https://app.clickup.com/t/knavr6)

2021-05-31 13:11 UTC, lpboucher commented
Task linked: [CU-knavr6 Clamp pipe](https://app.clickup.com/t/knavr6)

2021-05-31 20:56 UTC, lpboucher requested changes
Please rebase onto develop before making corrections

2021-05-31 20:56 UTC, lpboucher commented on src/app/shared/components/grid-list/grid-list.component.ts
> +    constructor(private clamp: ClampPipe) { }
variable name should be clampPipe, to better represent what it is

2021-05-31 20:56 UTC, lpboucher commented on src/app/shared/components/grid-list/grid-list.component.ts
> +        const MAX_COLUMN_COUNT = 12;
const variable should be defined as below @Input at the top of the class, or event potentially outside the class

2021-06-01 18:58 UTC, lpboucher approved these changes

2021-06-01 18:58 UTC, merged