Use-actual-api_CU-m18rxy
lpboucher/dak-coffee-wholesale pull request #41
Opened 2021-06-14 07:40 UTC by a-wilkes

2021-06-14 07:40 UTC, a-wilkes commented
Task linked: [CU-m18rxy Use actual api](https://app.clickup.com/t/m18rxy)

2021-06-14 07:40 UTC, lpboucher commented
Task linked: [CU-m18rxy Use actual api](https://app.clickup.com/t/m18rxy)

2021-06-14 19:40 UTC, lpboucher requested changes

2021-06-14 19:40 UTC, lpboucher commented on src/app/core/products/coffee-api.service.ts
>      getCoffee(slug: string): Observable<Coffee | undefined> {
i think we can remove the undefined type

2021-06-14 19:40 UTC, lpboucher commented on src/app/core/products/merchandise-api.service.ts
>      getMerchandiseItem(slug: string): Observable<Merchandise | undefined> {
i think we can remove the undefined type

2021-06-14 19:40 UTC, lpboucher commented on src/app/core/products/product-api.service.ts
> +            .pipe(map((products: Product[][]) => flatten(products)));
i agree with you this is hard to understand. Let's revisit at a later point. I think we can one/a combination of rxjs operators that do a better job of conveying what is happening here

2021-06-14 19:40 UTC, lpboucher commented on src/app/core/products/product-api.service.ts
> +            case undefined: /* fallthrough */
is this needed?

fallthrough will just fall to the default case no? Also, the default case in this example should be all

In any case, use a hashmap. Switch statements have O(n) complexity, while objects (with unique keys) are O(1)

I prefer) use an object (e.g dict) where the keys are the product types (all, coffee, etc.) the values are the returned observables.

And then simply return dict[productType] || dict["all"].

2021-06-19 16:01 UTC, lpboucher approved these changes

2021-06-19 16:01 UTC, merged