reusable-widget-component_CU-md8hfd
lpboucher/dak-coffee-wholesale pull request #44
Opened 2021-06-14 10:26 UTC by a-wilkes

2021-06-14 10:26 UTC, a-wilkes commented
Task linked: [CU-md8hfd reusable widget component](https://app.clickup.com/t/md8hfd)

2021-06-14 10:26 UTC, lpboucher commented
Task linked: [CU-md8hfd reusable widget component](https://app.clickup.com/t/md8hfd)

2021-06-14 20:24 UTC, lpboucher requested changes
Well done.

The only comment is regarding cart-widget and wallet-widget. You can remove the full componets (directory, scss, ts, html) and simply include the html in the sidebar directly

2021-06-19 16:40 UTC, lpboucher approved these changes

2021-06-19 16:40 UTC, merged