Notification-modal_CU-mfd024
lpboucher/dak-coffee-wholesale pull request #50
Opened 2021-06-15 14:00 UTC by a-wilkes

2021-06-15 14:00 UTC, a-wilkes commented
Task linked: [CU-mfd024 Notification modal](https://app.clickup.com/t/mfd024)

2021-06-15 14:01 UTC, lpboucher commented
Task linked: [CU-mfd024 Notification modal](https://app.clickup.com/t/mfd024)

2021-06-19 18:31 UTC, lpboucher requested changes

2021-06-19 18:31 UTC, lpboucher commented on src/app/modules/products/components/featured-product-card/featured-product-card.component.html
> +            <button class="featured-product-card-body-get-notified" (click)="showModal()">Get notified</button>
the method name should always refer to the user action. Here, we should use onGetNotifiedClicked

2021-06-19 18:31 UTC, lpboucher commented on src/app/modules/products/components/get-notified-confirmation-modal/get-notified-confirmation-modal.component.ts
> +export class GetNotifiedConfirmationModalComponent {
not a big fan of this component name. We should change the name of the component to NotificationModal.

Also, we should change the file names accordingly

2021-06-22 18:34 UTC, lpboucher approved these changes

2021-06-22 18:34 UTC, merged