Skeleton-loaders_CU-mhdp9g
lpboucher/dak-coffee-wholesale pull request #54
Opened 2021-06-16 11:32 UTC by a-wilkes

2021-06-16 11:32 UTC, a-wilkes commented
Task linked: [CU-mhdp9g Skeleton loaders](https://app.clickup.com/t/mhdp9g)

2021-06-16 11:32 UTC, lpboucher commented
Task linked: [CU-mhdp9g Skeleton loaders](https://app.clickup.com/t/mhdp9g)

2021-06-16 11:39 UTC, a-wilkes commented
I had to put the HTML and CSS in the pages and not the respective components since the pages deal with the async pipes and the components just receive the values. Switching this around (at least for the product and featured product cards) seems awkward at best, since the observables unwrap to an array of products. We'd need to restructure all the product services if we wanted an array of observables of products to allow the components to handle the async pipes instead. What do you think?

2021-06-19 19:10 UTC, lpboucher requested changes
This is a very good start! We jsut need to tweak it a bit:

See here:
https://user-images.githubusercontent.com/1252570/50053778-d4e0d900-018e-11e9-9de7-fad6f9fddd9e.gif

notice how the facebook skeleton exmaple combines multiple loaders (circle, full width etc.) to give the appearance that the loader knows what data it is expecting.

We should so the same. E.g. for product-card, our loader should have a large square at the top (as a placeholder for the image), then a few short ones (as placeholders for titles, arietal etc), two short ones (for price and add to card button), etc.

2021-06-19 19:10 UTC, lpboucher commented on src/app/modules/products/pages/product/product.page.html
> +        </ng-container>
this is a good start.

the ngx-skeleton-loader and its ngIf should be in the component that it replaces. Here, in featured-product-card, we should check whether the product is available and if not, display the loader. Same for product-card and product-detail

The page components should not know whether the result will be a loader or an actual component, they should only be concerned about what will take up that specific space in the layout

2021-06-19 19:10 UTC, lpboucher commented on src/app/modules/products/pages/product/product.page.html
> +        <ng-container *ngIf="products$ | async as products; else productsLoading">
as above, move to product-card

2021-06-19 19:10 UTC, lpboucher commented on src/app/modules/products/pages/single-product/single-product.page.html
> +    <app-product-detail [product]="product"></app-product-detail>
as above, move to product-detail

2021-06-19 19:10 UTC, lpboucher commented on src/app/modules/products/products.module.ts
> +import { NgxSkeletonLoaderModule } from "ngx-skeleton-loader";
these loaders may be used for other modules as well. Therefore, they should be imported in the shared module

2021-06-22 19:49 UTC, lpboucher requested changes

2021-06-22 19:49 UTC, lpboucher commented on src/app/modules/products/components/featured-product-card/featured-product-card.component.html
> +<ng-container *ngIf="product != null; else showLoader">
I dont like how there are two templates and two ngIfs (one in product-page and one in the card components

Feels like we are checking the same condition twice.

Let's move all the html for the loaders in their own components and then add them in the product-page:

`
<app-grid-list [itemColumnSpan]=2 [gridGap]=4>
        <ng-container *ngIf="featuredProducts$ | async as featuredProducts; else featuredProductsLoading">
            <app-featured-product-card *ngFor="let product of featuredProducts" [product]="product"></app-featured-product-card>
        </ng-container>
        <ng-template #featuredProductsLoading>
            <app-featured-product-card-loader></app-featured-product-card-loader>
        </ng-template>
    </app-grid-list>
`

2021-06-27 13:20 UTC, lpboucher approved these changes
Nicely done. I realized that we may run into some issues if our observable return falsy values (edge case) so I added a loader pipe that we can use to check if the observable is loading or has an error.

Skeletons look really good

2021-06-27 13:23 UTC, merged