Register-method_CU-mtarx3
lpboucher/dak-coffee-wholesale pull request #56
Opened 2021-06-21 15:17 UTC by a-wilkes

2021-06-21 15:17 UTC, a-wilkes commented
Task linked: [CU-mtarx3 Register method](https://app.clickup.com/t/mtarx3)

2021-06-22 15:39 UTC, lpboucher requested changes

2021-06-22 15:39 UTC, lpboucher commented on src/app/shared/models/classes/new-customer.class.ts
> +type Sector = "cafe" | "restaurant" | "office" | "subscription box" | "reseller";
we should define this in a separate type file

2021-06-22 15:39 UTC, lpboucher commented on src/app/shared/models/classes/new-customer.class.ts
> +    constructor(
this class should use the same structure as the other classes we have defined:

1) it should use a newCustomerShape in the constructor that is of type Partial<NewCustomer>
2) all class variables should be initialized as null, false, [], {}
3) setting the initial values is done inside an if block: 
`if (newCustomerShape != null) {
            if (newCustomerShape.id != null) {
                this.id = newCustomerShape.id;
            }
}
`

2021-06-23 18:42 UTC, lpboucher approved these changes

2021-06-23 18:42 UTC, merged