Modals-refactoring_CU-mt95zj
lpboucher/dak-coffee-wholesale pull request #59
Opened 2021-06-22 08:28 UTC by a-wilkes

2021-06-22 08:28 UTC, a-wilkes commented
Task linked: [CU-mt95zj Modals refactoring](https://app.clickup.com/t/mt95zj)

2021-06-22 08:28 UTC, lpboucher commented
Task linked: [CU-mt95zj Modals refactoring](https://app.clickup.com/t/mt95zj)

2021-06-27 13:41 UTC, lpboucher requested changes

2021-06-27 13:41 UTC, lpboucher commented on src/app/modules/backbone/backbone.common.ts
> +import { SamplesConfirmationModalComponent } from "@shared/components/modals";
this component should be exported from the shared module, like other modals

When we export components from a module, they become available in other modules. That is why we do not need to import them in multiple places and it is also why we use this shared module

2021-07-03 14:29 UTC, lpboucher approved these changes

2021-07-03 14:29 UTC, merged