Request-access-form_CU-mtarfc
lpboucher/dak-coffee-wholesale pull request #60
Opened 2021-06-22 14:58 UTC by a-wilkes

2021-06-22 14:58 UTC, a-wilkes commented
Task linked: [CU-mtarfc Request access form](https://app.clickup.com/t/mtarfc)

2021-06-27 14:03 UTC, lpboucher requested changes
I have updated import statements, make sure you pull before making changes

2021-06-27 14:03 UTC, lpboucher commented on src/app/modules/authentication/components/request-access-form/request-access-form.component.ts
> +    private control(name: string): AbstractControl | null {
i find this a bit redundant. It is sufficient to call requestAccessForm.get in the getters...

2021-06-27 14:03 UTC, lpboucher commented on src/app/modules/authentication/components/request-access-form/request-access-form.component.ts
> +    private matchPasswordsValidator(): ValidatorFn {
this is really good.

What we can do in Angular is define our own validators and pass them in the form control init array

I will create another ticket and we can refactor.

2021-06-27 14:03 UTC, lpboucher commented on src/app/modules/authentication/components/request-access-form/request-access-form.component.scss
> +    @apply h-screen;
using h-screen limits the background height to the height of the screen.

Here, since the form is longer than the height of the screen, we have a white bar at the bottom.

Instead, the request-access container should derive its height from the height of its child.

On mobile, there is a margin at the top. We should keep it for all devices and have the same at the bottom.

2021-07-03 14:42 UTC, lpboucher approved these changes

2021-07-03 14:42 UTC, merged