Product-detail-default-options_CU-nner2e
lpboucher/dak-coffee-wholesale pull request #78
Opened 2021-07-07 15:12 UTC by a-wilkes

2021-07-07 15:12 UTC, a-wilkes commented
Task linked: [CU-nner2e Product-detail default options](https://app.clickup.com/t/nner2e)

2021-07-07 15:12 UTC, lpboucher commented
Task linked: [CU-nner2e Product-detail default options](https://app.clickup.com/t/nner2e)

2021-07-07 15:12 UTC, lpboucher commented
Task linked: [CU-nhbe2j Add quantity input to product](https://app.clickup.com/t/nhbe2j)

2021-07-07 15:17 UTC, a-wilkes commented
I branched this from [Add-quantity-input-to-product](https://github.com/lpboucher/dak-coffee-wholesale/pull/74) since it already had the forms and controls set up which this PR needed to change/subscribe to changes to.

2021-07-11 11:32 UTC, lpboucher commented
Got it. That's fine.

We should probably also merge develop into this branch and then change the destination branch to develop given that I merged a lot of tickets this weekend

2021-07-11 11:33 UTC, lpboucher requested changes
I think this is quite extensive and can likely be simplified.

I will update the ticket with more information. Maybe as an indication, we will use the directive (from the tutorial) that we had looked at previously

2021-07-16 06:09 UTC, lpboucher approved these changes

2021-07-16 06:09 UTC, lpboucher commented on src/app/shared/directives/bind-query-params.directive.ts
> +    }
I find this method a bit clunky. reduce is not correct operator here. Here are two solutions:

1) .every: use .every on the array returned from Object.keys and compare the values against the other object's values. If it is true one way it is also true the other way. .every returns a boolean so it fits nicely here
2) When trying to check deep equality of objects, you can use toJSON and compare the resulting string. The caveat is that property order is important so if we thing that order of properties is not guaranteed then we would have to sort the keys

Also, it is likely that this type of equality check will be required at some later point. I have moved the logic to a utils/helper file

2021-07-16 06:11 UTC, merged