Product-service_CU-jfaz7a
lpboucher/dak-coffee-wholesale pull request #8
Opened 2021-05-10 09:52 UTC by a-wilkes

2021-05-10 09:52 UTC, a-wilkes commented
Task linked: [CU-jfaz7a Product service](https://app.clickup.com/t/jfaz7a)

2021-05-10 09:52 UTC, lpboucher commented
Task linked: [CU-jfaz7a Product service](https://app.clickup.com/t/jfaz7a)

2021-05-10 16:21 UTC, lpboucher requested changes
simple changes to be made. Make sure to pull before making further changes, I adjusted double quotes

2021-05-10 16:21 UTC, lpboucher commented on src/app/core/products/product.service.ts
> +
ngOnInit should not be used.

Services are not part on the render cycle and so lifecycle methods do not apply

2021-05-10 16:21 UTC, lpboucher commented on src/app/modules/products/components/product-list/product-list.component.ts
> +import { ProductService } from '@app/core/products/product.service';
here, we have an alias path for the core module, so we can import as:
"@core/products/product.service"

you can see all aliases in the file tsconfig.json

2021-05-10 16:21 UTC, lpboucher commented on src/app/core/products/product.service.ts
> +
see comment below, can be imported from @shared

2021-05-11 12:39 UTC, lpboucher approved these changes

2021-05-11 12:39 UTC, merged